# Generated by Django 4.1 on 2023-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='kekw', max_length=1000),
            preserve_default=False,
        ),
    ]
