# Generated by Django 4.1 on 2023-10-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generic', '0003_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
