# Generated by Django 4.1 on 2023-10-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apiview', '0002_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='hello everythin', max_length=1000),
            preserve_default=False,
        ),
    ]
